### ISSUE TITLE
About the UID issue of the mainpage 

### ISSUE THREAD

**Issue by xiangxinyue** [AspireUni/Aspire#82]
**Describe the bug**
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building RootPage(dirty, state: _RootPageState#e08d3):
flutter: setState() or markNeedsBuild() called during build.
flutter: This Overlay widget cannot be marked as needing to build because the framework is already in the
flutter: process of building widgets.  A widget can be marked as needing to be built during the build phase
flutter: only if one of its ancestors is currently building. This exception is allowed because the framework
flutter: builds parent widgets before children, which means a dirty descendant will always be built.
flutter: Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   Overlay-[LabeledGlobalKey<OverlayState>#9f575]
flutter: The widget which was currently being built when the offending call was made was:
flutter:   RootPage
flutter:
flutter: The relevant error-causing widget was:
flutter:   RootPage file:///Users/xinyuexiang/Desktop/MentorApp/lib/navigation/root.dart:15:33
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4167:11)
flutter: #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4182:6)
flutter: #2      State.setState (package:flutter/src/widgets/framework.dart:1253:14)
flutter: #3      OverlayState.rearrange (package:flutter/src/widgets/overlay.dart:415:5)
flutter: #4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3069:16)
flutter: #5      NavigatorState.push (package:flutter/src/widgets/navigator.dart:3297:5)
flutter: #6      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:3190:12)
flutter: #7      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:1529:34)
flutter: #8      _RootPageState.build (package:aspire/FTU/rootpage.dart:83:21)
flutter: #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
flutter: #11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
flutter: #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
flutter: #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #22     _invoke (dart:ui/hooks.dart:261:10)
flutter: #23     _drawFrame (dart:ui/hooks.dart:219:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2334 pos 18: '!navigator._debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      _RouteEntry.handlePush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2334:18)
#3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:398:15)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncComplete.<anonymous closure> (dart:as<…>

**Expected behavior**
After we login, we jump to the main page, the error shouldn't come out.

**Comment by xiangxinyue** [comment]
Fixed
